fixed bug in 50nodes-exp which delete everything added isAdmin(char*) which (in future versions) reads the witness from the wallet (when rpc newpostmsg is launched) cleaned accumunet.cpp with faster conversion functions and standard v0.1 prime hashing added new (incomplete) genesis transaction with the accumulator added accumulator to the TxToJSON function

diff --git a/50nodes-exp b/50nodes-exp
--- a/50nodes-exp
+++ b/50nodes-exp
@@ -118,8 +118,10 @@ elif [ "$1" = "stop" ]; then
     if [ "$2" != "pause" ]; then
 	for i in $(seq -f %02g 1 $NUM_NODI)
 	do
+	    set -e #exit on error or it will delete everything
 	    cd /tmp/nodo$i
 	    ls | grep -v debug.log | xargs rm -rf
+	    set +e
 	done
 	echo "file cancellati"
     fi
